version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:5ea192ed361b6c4f96879eada6b6df0ed26797914fb6407a8880e7d565961c33
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:d8d96b41c1e885e4dafeaee92464bd18bb545d66ee83d1439b109d718c9da045
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:81a45a529007d205974e4c3c6fddeea110208dd0df3c8f80b41709eab0605407
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
