version: 2.1

commands:
  run-npm-test:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run lint
      - run: npm test
jobs:
  node-v6:
    docker:
      - image: circleci/node:6@sha256:c34cdf483b3693ced4ed5ed40e2df60194ec215531febeadf7eec1004f6ada40
    steps:
      - run-npm-test
  node-v8:
    docker:
      - image: circleci/node:8@sha256:748c1e3cff6c820dd248db15268d004fc22ba8c26863fb6d8571e9fb5835d295
    steps:
      - run-npm-test
  node-v10:
    docker:
      - image: circleci/node:10@sha256:66a03ccc718ffb0aaa5d8518f3e27c5608ccebe60b818299c0090c8aaaf54448
    steps:
      - run-npm-test

workflows:
  multiple_builds:
    jobs:
      - node-v6
      - node-v8
      - node-v10
